# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors:
  jdk-8:
    docker:
      - image: adoptopenjdk/openjdk8:jdk8u202-b08-alpine
  jdk-11:
    docker:
      - image: adoptopenjdk/openjdk11:jdk-11.0.2.9-alpine

commands:
  run-build:
    parameters:
      jdk:
        type: string
    steps:
      - checkout

      - restore_cache:
          name: Restore Maven repository cache
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-v1-jdk-<< parameters.jdk >>-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-jdk-<< parameters.jdk >>-{{ .Branch }}-
            - maven-repo-v1-jdk-<< parameters.jdk >>-

      - restore_cache:
          name: Restore maven wrapper cache
          key: maven-wrapper-v1-jdk-<< parameters.jdk >>-{{ checksum ".mvn/wrapper/maven-wrapper.properties" }}

      - save_cache:
          name: Save Maven repository cache
          paths:
            - ~/.m2
          key: maven-repo-v1-jdk-<< parameters.jdk >>-{{ .Branch }}-{{ checksum "pom.xml" }}

      - save_cache:
          name: Save maven wrapper cache
          paths:
            - .mvn/wrapper/maven-wrapper.jar
          key: maven-wrapper-v1-jdk-<< parameters.jdk >>-{{ checksum ".mvn/wrapper/maven-wrapper.properties" }}

      - run:
          name: Run test
          command: ./mvnw test -Pdistro,errorLogging -DskipTests=false -B -V

      - run:
          name: Save test results
          command: |
              mkdir -p ~/junit/
              find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit



jobs:
  build-jdk8:
    executor: jdk-8

    working_directory: ~/flowable-engine

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - run-build:
          jdk: "8"

  build-jdk11:
    executor: jdk-11

    working_directory: ~/flowable-engine

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - run-build:
          jdk: "11"

workflows:
  version: 2
  build_test:
    jobs:
      - build-jdk8
      - build-jdk11


